export enum Role {
  ADMIN = 'ADMIN',
  PM = 'PM',
  MEMBER = 'MEMBER',
  LEADERSHIP = 'LEADERSHIP',
}

export enum TaskStatus {
  TODO = 'TODO',
  IN_PROGRESS = 'IN_PROGRESS',
  DONE = 'DONE',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  RETURNED = 'RETURNED',
  CANCELLED = 'CANCELLED',
}

export enum ProjectStatus {
  PLANNING = 'PLANNING',
  ACTIVE = 'ACTIVE',
  ON_HOLD = 'ON_HOLD',
  CLOSED = 'CLOSED',
}

export enum ProjectType {
  OSDC = 'OSDC',
  PKG = 'PKG',
}

export enum EmployeeLevel {
  JUNIOR = 'JUNIOR',
  MID = 'MID',
  SENIOR = 'SENIOR',
  EXPERT = 'EXPERT',
}

export enum NotificationType {
  TASK_OVERDUE = 'TASK_OVERDUE',
  TASK_DUE_TODAY = 'TASK_DUE_TODAY',
  TASK_DUE_SOON = 'TASK_DUE_SOON',
  TASK_APPROVED = 'TASK_APPROVED',
  TASK_RETURNED = 'TASK_RETURNED',
  TASK_CANCELLED = 'TASK_CANCELLED',
  TASK_PENDING = 'TASK_PENDING',
  RESOURCE_EXPIRING = 'RESOURCE_EXPIRING',
  RESOURCE_OVERLOAD = 'RESOURCE_OVERLOAD',
  EFFORT_NEAR_BUDGET = 'EFFORT_NEAR_BUDGET',
  EFFORT_OVER_BUDGET = 'EFFORT_OVER_BUDGET',
  BUDGET_NEAR_LIMIT = 'BUDGET_NEAR_LIMIT',
  BUDGET_EXCEEDED = 'BUDGET_EXCEEDED',
}

export enum AlertJobType {
  CHECK_ALL_ALERTS = 'CHECK_ALL_ALERTS',
  CHECK_TASK_ALERTS = 'CHECK_TASK_ALERTS',
  CHECK_RESOURCE_ALERTS = 'CHECK_RESOURCE_ALERTS',
  CHECK_BUDGET_ALERTS = 'CHECK_BUDGET_ALERTS',
  SEND_EMAIL = 'SEND_EMAIL',
  SEND_PUSH = 'SEND_PUSH',
}

export enum BudgetCurrency {
  VND = 'VND',
  USD = 'USD',
}
