BEGIN;
ALTER TABLE "skills" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "skills_tenant_id_idx" ON "skills" ("tenant_id");
ALTER TABLE "employee_skills" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "employee_skills_tenant_id_idx" ON "employee_skills" ("tenant_id");
ALTER TABLE "employee_rates" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "employee_rates_tenant_id_idx" ON "employee_rates" ("tenant_id");
ALTER TABLE "time_logs" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "time_logs_tenant_id_idx" ON "time_logs" ("tenant_id");
ALTER TABLE "work_statuses" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "work_statuses_tenant_id_idx" ON "work_statuses" ("tenant_id");
ALTER TABLE "timesheet_records" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "timesheet_records_tenant_id_idx" ON "timesheet_records" ("tenant_id");
ALTER TABLE "alert_configs" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "alert_configs_tenant_id_idx" ON "alert_configs" ("tenant_id");
ALTER TABLE "notifications" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "notifications_tenant_id_idx" ON "notifications" ("tenant_id");
ALTER TABLE "push_tokens" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "push_tokens_tenant_id_idx" ON "push_tokens" ("tenant_id");
ALTER TABLE "telegram_configs" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "telegram_configs_tenant_id_idx" ON "telegram_configs" ("tenant_id");
ALTER TABLE "telegram_messages" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "telegram_messages_tenant_id_idx" ON "telegram_messages" ("tenant_id");
ALTER TABLE "process_user_tasks" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "process_user_tasks_tenant_id_idx" ON "process_user_tasks" ("tenant_id");
ALTER TABLE "process_activity_logs" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "process_activity_logs_tenant_id_idx" ON "process_activity_logs" ("tenant_id");
ALTER TABLE "bug_tasks" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "bug_tasks_tenant_id_idx" ON "bug_tasks" ("tenant_id");
ALTER TABLE "bug_attachments" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "bug_attachments_tenant_id_idx" ON "bug_attachments" ("tenant_id");
ALTER TABLE "bug_comments" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "bug_comments_tenant_id_idx" ON "bug_comments" ("tenant_id");
ALTER TABLE "bug_tags" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "bug_tags_tenant_id_idx" ON "bug_tags" ("tenant_id");
ALTER TABLE "user_permissions" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "user_permissions_tenant_id_idx" ON "user_permissions" ("tenant_id");
ALTER TABLE "user_module_roles" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "user_module_roles_tenant_id_idx" ON "user_module_roles" ("tenant_id");
ALTER TABLE "audit_logs" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "audit_logs_tenant_id_idx" ON "audit_logs" ("tenant_id");
ALTER TABLE "user_groups" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "user_groups_tenant_id_idx" ON "user_groups" ("tenant_id");
ALTER TABLE "group_permissions" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "group_permissions_tenant_id_idx" ON "group_permissions" ("tenant_id");
ALTER TABLE "group_memberships" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "group_memberships_tenant_id_idx" ON "group_memberships" ("tenant_id");
ALTER TABLE "group_org_access" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "group_org_access_tenant_id_idx" ON "group_org_access" ("tenant_id");
ALTER TABLE "contract_allowances" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "contract_allowances_tenant_id_idx" ON "contract_allowances" ("tenant_id");
ALTER TABLE "leave_types" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "leave_types_tenant_id_idx" ON "leave_types" ("tenant_id");
ALTER TABLE "overtime_requests" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "overtime_requests_tenant_id_idx" ON "overtime_requests" ("tenant_id");
ALTER TABLE "expenses" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "expenses_tenant_id_idx" ON "expenses" ("tenant_id");
ALTER TABLE "expense_items" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "expense_items_tenant_id_idx" ON "expense_items" ("tenant_id");
ALTER TABLE "contract_milestones" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "contract_milestones_tenant_id_idx" ON "contract_milestones" ("tenant_id");
ALTER TABLE "invoice_items" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "invoice_items_tenant_id_idx" ON "invoice_items" ("tenant_id");
ALTER TABLE "asset_assignments" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "asset_assignments_tenant_id_idx" ON "asset_assignments" ("tenant_id");
ALTER TABLE "asset_maintenance" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "asset_maintenance_tenant_id_idx" ON "asset_maintenance" ("tenant_id");
ALTER TABLE "chart_of_accounts" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "chart_of_accounts_tenant_id_idx" ON "chart_of_accounts" ("tenant_id");
ALTER TABLE "journal_entries" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "journal_entries_tenant_id_idx" ON "journal_entries" ("tenant_id");
ALTER TABLE "journal_lines" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "journal_lines_tenant_id_idx" ON "journal_lines" ("tenant_id");
ALTER TABLE "training_programs" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "training_programs_tenant_id_idx" ON "training_programs" ("tenant_id");
ALTER TABLE "training_records" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "training_records_tenant_id_idx" ON "training_records" ("tenant_id");
ALTER TABLE "performance_reviews" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "performance_reviews_tenant_id_idx" ON "performance_reviews" ("tenant_id");
ALTER TABLE "employee_tax_profiles" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "employee_tax_profiles_tenant_id_idx" ON "employee_tax_profiles" ("tenant_id");
ALTER TABLE "dependents" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "dependents_tenant_id_idx" ON "dependents" ("tenant_id");
ALTER TABLE "allowance_types" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "allowance_types_tenant_id_idx" ON "allowance_types" ("tenant_id");
ALTER TABLE "bonus_types" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "bonus_types_tenant_id_idx" ON "bonus_types" ("tenant_id");
ALTER TABLE "employee_bonuses" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "employee_bonuses_tenant_id_idx" ON "employee_bonuses" ("tenant_id");
ALTER TABLE "employee_yearly_tax_summaries" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "employee_yearly_tax_summaries_tenant_id_idx" ON "employee_yearly_tax_summaries" ("tenant_id");
ALTER TABLE "employee_allowances" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "employee_allowances_tenant_id_idx" ON "employee_allowances" ("tenant_id");
ALTER TABLE "okr_key_results" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "okr_key_results_tenant_id_idx" ON "okr_key_results" ("tenant_id");
ALTER TABLE "kpi_metrics" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "kpi_metrics_tenant_id_idx" ON "kpi_metrics" ("tenant_id");
ALTER TABLE "kpi_records" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "kpi_records_tenant_id_idx" ON "kpi_records" ("tenant_id");
ALTER TABLE "revenue_targets" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "revenue_targets_tenant_id_idx" ON "revenue_targets" ("tenant_id");
ALTER TABLE "kb_categories" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "kb_categories_tenant_id_idx" ON "kb_categories" ("tenant_id");
ALTER TABLE "customer_tickets" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "customer_tickets_tenant_id_idx" ON "customer_tickets" ("tenant_id");
ALTER TABLE "purchase_order_items" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "purchase_order_items_tenant_id_idx" ON "purchase_order_items" ("tenant_id");
ALTER TABLE "feed_posts" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "feed_posts_tenant_id_idx" ON "feed_posts" ("tenant_id");
ALTER TABLE "feed_reactions" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "feed_reactions_tenant_id_idx" ON "feed_reactions" ("tenant_id");
ALTER TABLE "automation_rules" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "automation_rules_tenant_id_idx" ON "automation_rules" ("tenant_id");
ALTER TABLE "automation_rule_logs" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "automation_rule_logs_tenant_id_idx" ON "automation_rule_logs" ("tenant_id");
ALTER TABLE "scheduled_reports" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "scheduled_reports_tenant_id_idx" ON "scheduled_reports" ("tenant_id");
ALTER TABLE "webhook_endpoints" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "webhook_endpoints_tenant_id_idx" ON "webhook_endpoints" ("tenant_id");
ALTER TABLE "webhook_logs" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "webhook_logs_tenant_id_idx" ON "webhook_logs" ("tenant_id");
ALTER TABLE "module_configs" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "module_configs_tenant_id_idx" ON "module_configs" ("tenant_id");
ALTER TABLE "meeting_rooms" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "meeting_rooms_tenant_id_idx" ON "meeting_rooms" ("tenant_id");
ALTER TABLE "room_bookings" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "room_bookings_tenant_id_idx" ON "room_bookings" ("tenant_id");
ALTER TABLE "vehicles" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "vehicles_tenant_id_idx" ON "vehicles" ("tenant_id");
ALTER TABLE "vehicle_requests" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "vehicle_requests_tenant_id_idx" ON "vehicle_requests" ("tenant_id");
ALTER TABLE "budget_plans" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "budget_plans_tenant_id_idx" ON "budget_plans" ("tenant_id");
ALTER TABLE "budget_lines" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "budget_lines_tenant_id_idx" ON "budget_lines" ("tenant_id");
ALTER TABLE "budget_transactions" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "budget_transactions_tenant_id_idx" ON "budget_transactions" ("tenant_id");
ALTER TABLE "calendar_events" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "calendar_events_tenant_id_idx" ON "calendar_events" ("tenant_id");
ALTER TABLE "project_cost_snapshots" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "project_cost_snapshots_tenant_id_idx" ON "project_cost_snapshots" ("tenant_id");
ALTER TABLE "project_cost_by_employees" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "project_cost_by_employees_tenant_id_idx" ON "project_cost_by_employees" ("tenant_id");
ALTER TABLE "salary_bands" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "salary_bands_tenant_id_idx" ON "salary_bands" ("tenant_id");
ALTER TABLE "salary_review_suggestions" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "salary_review_suggestions_tenant_id_idx" ON "salary_review_suggestions" ("tenant_id");
ALTER TABLE "job_titles" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "job_titles_tenant_id_idx" ON "job_titles" ("tenant_id");
ALTER TABLE "positions" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "positions_tenant_id_idx" ON "positions" ("tenant_id");
ALTER TABLE "position_histories" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "position_histories_tenant_id_idx" ON "position_histories" ("tenant_id");
ALTER TABLE "hr_decisions" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "hr_decisions_tenant_id_idx" ON "hr_decisions" ("tenant_id");
ALTER TABLE "work_history" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "work_history_tenant_id_idx" ON "work_history" ("tenant_id");
ALTER TABLE "salary_records" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "salary_records_tenant_id_idx" ON "salary_records" ("tenant_id");
ALTER TABLE "leave_policies" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "leave_policies_tenant_id_idx" ON "leave_policies" ("tenant_id");
ALTER TABLE "holiday_calendars" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "holiday_calendars_tenant_id_idx" ON "holiday_calendars" ("tenant_id");
ALTER TABLE "insurance_enrollments" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "insurance_enrollments_tenant_id_idx" ON "insurance_enrollments" ("tenant_id");
ALTER TABLE "social_insurance_books" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "social_insurance_books_tenant_id_idx" ON "social_insurance_books" ("tenant_id");
ALTER TABLE "insurance_events" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "insurance_events_tenant_id_idx" ON "insurance_events" ("tenant_id");
ALTER TABLE "attendance_records" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "attendance_records_tenant_id_idx" ON "attendance_records" ("tenant_id");
ALTER TABLE "monthly_attendances" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "monthly_attendances_tenant_id_idx" ON "monthly_attendances" ("tenant_id");
ALTER TABLE "work_shifts" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "work_shifts_tenant_id_idx" ON "work_shifts" ("tenant_id");
ALTER TABLE "shift_assignments" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "shift_assignments_tenant_id_idx" ON "shift_assignments" ("tenant_id");
ALTER TABLE "work_schedules" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "work_schedules_tenant_id_idx" ON "work_schedules" ("tenant_id");
ALTER TABLE "work_schedule_phases" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "work_schedule_phases_tenant_id_idx" ON "work_schedule_phases" ("tenant_id");
ALTER TABLE "work_schedule_enrollments" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "work_schedule_enrollments_tenant_id_idx" ON "work_schedule_enrollments" ("tenant_id");
ALTER TABLE "notification_preferences" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "notification_preferences_tenant_id_idx" ON "notification_preferences" ("tenant_id");
ALTER TABLE "saved_filter_presets" ADD COLUMN IF NOT EXISTS "tenant_id" text;
CREATE INDEX IF NOT EXISTS "saved_filter_presets_tenant_id_idx" ON "saved_filter_presets" ("tenant_id");
COMMIT;
